import Link from "next/link";
import Reveal from "./Reveal";
import BlogArchDiagram from "./BlogArchDiagram";
import DiagramAnimator from "./DiagramAnimator";

// The write-up for /howdidimakethis/blog -- how the /blog ("Writing")
// pages actually work. Every technical claim here is real, pulled from
// content/blog, lib/blog/posts.ts, and app/(site)/blog in this repo, not
// a generic description of "how you'd build a blog".
export default function BlogContent() {
  return (
    <>
      <div className="sc-hero">
        <p className="sc-boot-line">
          $ whoami<br />
          <span className="sc-ok">&gt;</span> someone reading a post on /blog
        </p>
        <p className="sc-boot-line">
          $ cat ./README.md | head -2<br />
          <span className="sc-ok">&gt;</span> a blog with no CMS, no database, and no new GCP resources
        </p>
        <p className="sc-boot-line">
          $ ./reveal --app=blog<br />
          <span className="sc-ok">&gt;</span> booting write-up...
        </p>
        <h1 className="sc-hero-title">
          The whole feature is a folder of Markdown files.
          <span className="sc-cursor" aria-hidden="true" />
        </h1>
        <p className="sc-hero-sub">
          No third-party CMS, no new storage bucket, no serverless function. Posts are
          files in this repo, rendered into the same static export as
          every other page on the site.
        </p>
      </div>

      <Reveal>
        <div className="sc-section-head">
          <span className="sc-prompt">$</span> cat decisions.md
          <h2>why Markdown-in-repo, not a CMS or an S3 bucket</h2>
        </div>
        <p>
          The original idea was a local desktop app that generates
          standalone HTML pages and CRUD-manages them in a dedicated S3
          bucket, scanned client-side on load. Before building that, four
          options got laid out — repo-based Markdown won on three counts:
        </p>
        <p>
          <strong>Zero new infrastructure.</strong> No extra storage bucket,
          no new hosting config, no Cloud Function. Publishing a post rides
          the same GitHub Actions pipeline that already deploys everything
          else on this site.
        </p>
        <p>
          <strong>Real static HTML, for real link previews.</strong>{" "}
          Every post&apos;s title, body, and Open Graph tags are fully
          baked in at build time — not injected client-side — which
          matters because LinkedIn&apos;s link-preview scraper doesn&apos;t
          execute JavaScript. A client-scanned S3 bucket would&apos;ve
          needed extra work to make individual posts crawlable at all.
        </p>
        <p>
          <strong>Free consistency with the theme system.</strong> A post
          rendered through this site&apos;s own layout inherits the
          magazine/pixel/material/monochrome switcher automatically. A
          standalone HTML file generated by an external tool would have to
          duplicate that chrome, or drift from it the first time the site&apos;s
          design changes and old posts don&apos;t get regenerated.
        </p>
        <p>
          The honest trade-off: publishing means a git commit and a CI
          build (a minute or two of lag), not an instant edit. For a
          personal blog, that&apos;s a fair price.
        </p>
      </Reveal>

      <Reveal>
        <div className="sc-section-head">
          <span className="sc-prompt">$</span> cat pipeline.md
          <h2>from Markdown file to deployed page</h2>
        </div>
        <p>
          There&apos;s no request-time backend here — the interesting part
          of this architecture is a <em>build-time</em> pipeline, feeding
          infrastructure that already existed. Nothing new got provisioned
          in GCP for this feature at all.
        </p>
        <div className="sc-diagram">
          <DiagramAnimator>
            <BlogArchDiagram />
          </DiagramAnimator>
        </div>
        <p className="sc-diagram-caption">
          Everything above the dashed box happens once, during{" "}
          <code>next build</code>. Everything below it is what a
          visitor&apos;s browser actually does — fetch static HTML, then
          run a small amount of client-side JS for search and pagination.
        </p>
      </Reveal>

      <Reveal>
        <div className="sc-section-head">
          <span className="sc-prompt">$</span> cat lib/blog/posts.ts | grep export
          <h2>the render pipeline, in order</h2>
        </div>
        <div className="sc-timeline">
          <div className="sc-timeline-item">
            <strong>1.</strong> <code>gray-matter</code> splits a{" "}
            <code>.md</code> file into YAML frontmatter (title, date,
            excerpt, tags, an optional <code>draft</code> flag) and the
            Markdown body.
          </div>
          <div className="sc-timeline-item">
            <strong>2.</strong> Listing posts (<code>getAllPosts</code>,
            the index, tag pages) only ever reads frontmatter — the
            Markdown body is never parsed for a post that isn&apos;t being
            fully rendered, so the index doesn&apos;t pay for content it
            isn&apos;t showing.
          </div>
          <div className="sc-timeline-item">
            <strong>3.</strong> Rendering one post (<code>getPostBySlug</code>)
            runs the body through <code>remark</code> +{" "}
            <code>remark-gfm</code> + <code>remark-html</code>, with{" "}
            <code>sanitize: false</code> — posts are self-authored and
            trusted, the same model as the rest of the site, so raw HTML
            written inline in a post (an embedded YouTube{" "}
            <code>&lt;iframe&gt;</code>, say) passes straight through.
          </div>
          <div className="sc-timeline-item">
            <strong>4.</strong> <code>generateStaticParams</code> turns
            every published slug and tag into a route at build time —
            required by <code>output: &quot;export&quot;</code>, since every
            path has to be known before the static files exist. A draft
            or an unpublished slug simply isn&apos;t a route; it
            404s.
          </div>
          <div className="sc-timeline-item">
            <strong>5.</strong> <code>generateMetadata</code> sets each
            page&apos;s title, description, and Open Graph tags — this is
            what the LinkedIn share button&apos;s preview card actually
            reads.
          </div>
        </div>
      </Reveal>

      <Reveal>
        <div className="sc-section-head">
          <span className="sc-prompt">$</span> cat components/blog/BlogIndex.tsx | grep client
          <h2>tags, search, and pagination — all client-side, no new dependency</h2>
        </div>
        <p>
          <code>getAllPosts()</code> already runs at build time and its
          result gets passed straight into{" "}
          <code>&lt;BlogIndex posts=&#123;posts&#125; /&gt;</code>, a small{" "}
          <code>&quot;use client&quot;</code> component. Since that array is
          already sitting in the browser, three features fell out of it
          for close to free:
        </p>
        <p>
          <strong>Search</strong> is a plain <code>.filter()</code> over
          title, excerpt, and tags as you type — no search index file, no
          API route, no library. Fine at personal-blog scale; the point
          to reach for a build-time tool like Pagefind instead is if post
          bodies (not just excerpts) need to be searched, or the post
          count grows enough that shipping the whole list client-side
          stops being free.
        </p>
        <p>
          <strong>Tags</strong> reuse the same frontmatter field the
          Markdown pipeline already parses.{" "}
          <code>getAllTags()</code>/<code>getPostsByTag()</code> feed a{" "}
          <code>/blog/tags/[tag]</code> static route — which just renders{" "}
          <code>&lt;BlogIndex&gt;</code> again, pre-filtered. A tag page
          isn&apos;t a separate implementation; it&apos;s the index,
          scoped.
        </p>
        <p>
          <strong>Pagination</strong> is &quot;Load more&quot;, not{" "}
          <code>/blog/page/2</code> routes — the full list already has to
          be client-side for search to work, so slicing it further costs
          nothing extra, and a blog index&apos;s pagination state isn&apos;t
          something worth its own crawlable URL. Individual posts are
          what get shared and indexed, not the index&apos;s page 2.
        </p>
      </Reveal>

      <Reveal>
        <div className="sc-section-head">
          <span className="sc-prompt">$</span> cat components/LinkedInShareButton.tsx
          <h2>the LinkedIn button is a link, not an integration</h2>
        </div>
        <p>
          &quot;Publish to LinkedIn via a button&quot; could mean two very
          different things: a share-intent link, or a full API integration
          with a registered LinkedIn app, OAuth consent, and token storage.
          This is the first one — an anchor tag pointed at LinkedIn&apos;s
          own <code>share-offsite</code> URL, opened in a new tab. No
          credentials to manage, no token to refresh, nothing that can
          expire. The preview card it shows comes entirely from the{" "}
          <code>generateMetadata</code> Open Graph tags above.
        </p>
      </Reveal>

      <Reveal>
        <div className="sc-section-head">
          <span className="sc-prompt">$</span> ls content/blog/
          <h2>stack</h2>
        </div>
        <div className="sc-chip-grid">
          {[
            "Next.js static export (output: \"export\")",
            "gray-matter — frontmatter parsing",
            "remark + remark-gfm + remark-html",
            "generateStaticParams / generateMetadata",
            "Client-side search & \"Load more\" — no new dependency",
            "LinkedIn share-offsite link",
          ].map((item) => (
            <span key={item} className="sc-chip">
              {item}
            </span>
          ))}
        </div>
      </Reveal>

      <div className="sc-footer">
        <p style={{ margin: 0 }}>
          Curious how the rest of the site is built?{" "}
          <Link href="/howdidimakethis/ch-ai">Read how ch-ai.in itself is built</Link>, or{" "}
          <Link href="/howdidimakethis">see what else has a page like this</Link>.
        </p>
      </div>
    </>
  );
}
